(()=>{
const board=document.querySelector('#board'),svg=document.querySelector('#wires'),hint=document.querySelector('#hint'),status=document.querySelector('#status'),statusText=document.querySelector('#statusText'),count=document.querySelector('#count'),undo=document.querySelector('#undo'),sound=document.querySelector('#sound'),keys=[document.querySelector('#oneKey1'),document.querySelector('#oneKey2')],unit=document.querySelector('.combo-unit'),lamps=[...document.querySelectorAll('.lamp')],motor=document.querySelector('#motor'),socket=document.querySelector('#socket'),plug=motor.querySelector('.plug'),fixedTerms=[...document.querySelectorAll('.terminal')],buses=[...document.querySelectorAll('.bus')],choices=[...document.querySelectorAll('.choice')],supply=document.querySelector('.supply'),rod=document.querySelector('.rod');
let selected='brown',links=[],wireDrag=null,motorDrag=null,closed=[false,false],plugged=false,audioEnabled=true,audioCtx=null,tapSeq=0,plugOffset={x:0,y:0};
const allTerms=()=>[...document.querySelectorAll('.terminal')],tapRoot=id=>{const e=term(id);return e?.dataset.bus==='L'?'srcL':e?.dataset.bus==='N'?'srcN':e?.dataset.bus==='PE'?'srcPE':null};
const term=id=>document.querySelector('[data-id="'+id+'"]'),center=e=>{const b=board.getBoundingClientRect(),r=e.getBoundingClientRect();return{x:r.left+r.width/2-b.left,y:r.top+r.height/2-b.top}};
function audio(){if(!audioEnabled)return null;if(!audioCtx){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;audioCtx=new A()}if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(f,d,type='sine',v=.045,delay=0){const a=audio();if(!a)return;const o=a.createOscillator(),g=a.createGain(),t=a.currentTime+delay;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(a.destination);o.start(t);o.stop(t+d+.02)}
function play(n){if(n==='connect'){tone(520,.08);tone(720,.1,'sine',.03,.06)}if(n==='switch'){tone(210,.05,'square');tone(360,.05,'square',.025,.04)}if(n==='plug'){tone(180,.06,'square');tone(440,.09,'sine',.04,.05)}if(n==='fault'){tone(88,.35,'sawtooth',.07)}if(n==='success'){tone(523,.15);tone(659,.18,'sine',.04,.1);tone(784,.2,'sine',.035,.2)}if(n==='remove')tone(260,.1)}
function pathData(p){return p.length<2?'':'M '+p.map(q=>q.x+' '+q.y).join(' L ')}
function addPath(d,c){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class',c);svg.append(p)}
function points(l){const r=board.getBoundingClientRect(),p=l.points.map(q=>({x:q.x*r.width,y:q.y*r.height}));p[0]=center(term(l.a));p[p.length-1]=center(term(l.b));return p}
function graph(load='none'){const g={};function edge(a,b,index=null){(g[a]??=[]).push({to:b,index});(g[b]??=[]).push({to:a,index})}allTerms().forEach(t=>{const r=tapRoot(t.dataset.id);if(r)edge(r,t.dataset.id)});links.forEach((l,i)=>edge(l.a,l.b,i));if(closed[0])edge('sw1In','sw1Out');if(closed[1])edge('sw2In','sw2Out');if(load==='lamp1'||load==='all')edge('lamp1L','lamp1N');if(load==='lamp2'||load==='all')edge('lamp2L','lamp2N');if(plugged&&(load==='motor'||load==='all'))edge('outL','outN');return g}
function reach(start,g){const seen=new Set([start]),q=[start];while(q.length){const n=q.shift();for(const e of g[n]||[])if(!seen.has(e.to)){seen.add(e.to);q.push(e.to)}}return seen}
function pathLinks(start,end,g){const seen=new Set([start]),q=[start],prev={};while(q.length){const n=q.shift();if(n===end)break;for(const e of g[n]||[])if(!seen.has(e.to)){seen.add(e.to);prev[e.to]={from:n,index:e.index};q.push(e.to)}}if(!seen.has(end))return[];const out=[];for(let n=end;n!==start;){const p=prev[n];if(p.index!==null)out.push(p.index);n=p.from}return out}
function drawMotorLead(){const b=board.getBoundingClientRect(),m=motor.querySelector('.motor-shell').getBoundingClientRect(),p=plug.getBoundingClientRect(),a={x:m.left-b.left+14,y:m.bottom-b.top-7},z={x:p.left+p.width/2-b.left,y:p.top+p.height/2-b.top},d=`M ${a.x} ${a.y} C ${a.x-55} ${a.y+45}, ${z.x-50} ${z.y+30}, ${z.x} ${z.y}`;addPath(d,'motor-lead');addPath(d,'motor-lead-core')}
function draw(){svg.replaceChildren();const g=graph(),phase=reach('srcL',g),neutral=reach('srcN',g),earth=reach('srcPE',g),current=new Set([...pathLinks('srcL','srcN',graph('lamp1')),...pathLinks('srcL','srcN',graph('lamp2')),...pathLinks('srcL','srcN',graph('motor'))]);links.forEach((l,i)=>{const p=points(l),d=pathData(p);addPath(d,'shadow');addPath(d,'wire '+l.type);const live=phase.has(l.a)&&phase.has(l.b),ret=neutral.has(l.a)&&neutral.has(l.b),pe=earth.has(l.a)&&earth.has(l.b);if(live)addPath(d,'flow');if(current.has(i))addPath(d,'ac-current');if(pe&&l.type!=='earth')addPath(d,'flow')});if(wireDrag){const d=pathData(wireDrag.points);addPath(d,'shadow');addPath(d,'wire '+wireDrag.type+' preview')}drawMotorLead()}
function solve(state=closed){const ids=['srcL','srcN','srcPE',...allTerms().map(t=>t.dataset.id)],parent=Object.fromEntries(ids.map(x=>[x,x])),find=x=>parent[x]===x?x:(parent[x]=find(parent[x])),join=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a};allTerms().forEach(t=>{const r=tapRoot(t.dataset.id);if(r)join(r,t.dataset.id)});links.forEach(l=>join(l.a,l.b));if(state[0])join('sw1In','sw1Out');if(state[1])join('sw2In','sw2Out');const L=find('srcL'),N=find('srcN'),PE=find('srcPE'),is=(x,r)=>find(x)===r,short=L===N||L===PE,neutralEarth=N===PE,lampsOn=[is('lamp1L',L)&&is('lamp1N',N),is('lamp2L',L)&&is('lamp2N',N)],lampReverse=[is('lamp1L',N)&&is('lamp1N',L),is('lamp2L',N)&&is('lamp2N',L)],outPowered=is('outL',L)&&is('outN',N),outReverse=is('outL',N)&&is('outN',L),earthSafe=is('outPE',PE)&&is('rodPE',PE),motorRun=plugged&&outPowered;return{short,neutralEarth,lampsOn,lampReverse,outPowered,outReverse,earthSafe,motorRun}}
function nodeKind(x){const r=tapRoot(x);return r||x}function colorError(){return links.some(l=>{const ends=[nodeKind(l.a),nodeKind(l.b)];if(l.type==='brown')return ends.some(x=>x==='srcN'||x==='srcPE'||x==='rodPE'||x==='outN'||x==='outPE'||/^lamp[12]N$/.test(x));if(l.type==='blue')return ends.some(x=>x==='srcL'||x==='srcPE'||x==='rodPE'||x==='outL'||x==='outPE'||x.startsWith('sw')||/^lamp[12]L$/.test(x));if(l.type==='earth')return ends.some(x=>!['srcPE','rodPE','outPE'].includes(x));return false})}
function diagnose(){const now=solve(),off=solve([false,false]),s1=solve([true,false]),s2=solve([false,true]),both=solve([true,true]);let cls='hint',head='',text='';if(now.short){cls='hint error';head='FALLA GRAVE';text='La fase está unida directamente con neutro o tierra.'}else if(now.neutralEarth){cls='hint error';head='Unión N–PE indebida';text='Neutro y protección deben permanecer separados en el circuito final.'}else if(now.outReverse||now.lampReverse.some(Boolean)){head='Polaridad incorrecta';text='Corrige L y N en el toma o en uno de los focos.'}else if(off.lampsOn.some(Boolean)){head='Llave puenteada';text='Uno o ambos focos reciben fase sin atravesar su interruptor.'}else if(!(s1.lampsOn[0]&&!s1.lampsOn[1]&&!s2.lampsOn[0]&&s2.lampsOn[1]&&both.lampsOn.every(Boolean))){head='Control incorrecto';text='La primera llave debe controlar solo el foco 1 y la segunda solamente el foco 2.'}else if(!now.outPowered){head='Tomacorriente sin tensión';text='El toma necesita fase y neutro permanentes, independientes de ambas llaves.'}else if(!now.earthSafe){head='Funciona, pero no es seguro';text='Falta continuidad verde/amarilla entre toma, jabalina y PE.'}else if(colorError()){head='Código de colores incorrecto';text='Marrón para fase y retornos, celeste para neutro y verde/amarillo para PE.'}else if(!plugged){head='Cableado preparado';text='Las dos luces responden correctamente. Conecta la ficha para probar el toma.'}else if(now.motorRun){cls='hint ok';head='Prueba superada';text='Dos controles independientes, toma permanente y protección a tierra continua.'}else{head='Motor detenido';text='La ficha está colocada, pero el toma no presenta L y N correctos.'}return{now,cls,head,text}}
function update(){const d=diagnose();lamps.forEach((lamp,i)=>{lamp.classList.toggle('on',d.now.lampsOn[i]);lamp.querySelector('.bulb').style.setProperty('--level',d.now.lampsOn[i]?'1':'0')});keys.forEach((key,i)=>{key.setAttribute('aria-pressed',String(closed[i]));unit.classList.toggle('closed'+(i+1),closed[i]);unit.classList.toggle('current'+(i+1),closed[i]&&d.now.lampsOn[i]&&!d.now.short)});motor.classList.toggle('plugged',plugged);motor.classList.toggle('running',d.now.motorRun);motor.querySelector('.motor-note').textContent=plugged?(d.now.motorRun?'MOTOR EN MARCHA':'SIN ALIMENTACIÓN'):'ARRASTRA SOLO LA FICHA';status.className='status'+(d.now.short||d.now.neutralEarth?' error':d.cls==='hint ok'?' on':links.length?' ready':'');statusText.textContent=d.head;hint.className=d.cls;hint.innerHTML='<strong>'+d.head+':</strong> '+d.text;count.textContent=links.length+' cable'+(links.length===1?'':'s');undo.disabled=!links.length;document.querySelector('#brownLeft').textContent=links.filter(l=>l.type==='brown').length+' colocado(s)';document.querySelector('#blueLeft').textContent=links.filter(l=>l.type==='blue').length+' colocado(s)';document.querySelector('#earthLeft').textContent=links.filter(l=>l.type==='earth').length+' colocado(s)';allTerms().forEach(t=>t.classList.toggle('connected',links.some(l=>l.a===t.dataset.id||l.b===t.dataset.id)));draw()}
function select(t){selected=t;choices.forEach(c=>c.setAttribute('aria-pressed',String(c.dataset.type===t)));update()}choices.forEach(c=>c.onclick=()=>select(c.dataset.type));
function wireStart(e,explicit){audio();e.preventDefault();e.stopPropagation();const el=explicit||e.currentTarget;el.setPointerCapture?.(e.pointerId);wireDrag={start:el,type:selected,id:e.pointerId,points:[center(el)]};el.classList.add('active');draw()}
function nearestWireStart(e){const target=e.target;if(target.closest('.plug,.one-key,.key,.toggle')||(target.closest('.bus')&&!target.closest('.terminal')))return;let best=null,distance=36;for(const t of allTerms()){if(t.offsetParent===null)continue;const p=center(t),d=Math.hypot(e.clientX-board.getBoundingClientRect().left-p.x,e.clientY-board.getBoundingClientRect().top-p.y);if(d<distance){distance=d;best=t}}if(best){e.stopPropagation();wireStart(e,best)}}
function pointerMove(e){if(wireDrag&&wireDrag.id===e.pointerId){const b=board.getBoundingClientRect(),p={x:e.clientX-b.left,y:e.clientY-b.top},last=wireDrag.points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>6)wireDrag.points.push(p);draw()}if(motorDrag&&motorDrag.id===e.pointerId){plugOffset.x=motorDrag.ox+e.clientX-motorDrag.x;plugOffset.y=motorDrag.oy+e.clientY-motorDrag.y;plug.style.transform=`translate(${plugOffset.x}px,${plugOffset.y}px)`;plugged=false;update()}}
function pointerEnd(e){if(wireDrag&&wireDrag.id===e.pointerId){const from=wireDrag.start,last=wireDrag.points.at(-1);let dest=null,best=65;for(const t of allTerms()){if(t===from)continue;const p=center(t),d=Math.hypot(p.x-last.x,p.y-last.y);if(d<best){best=d;dest=t}}from.classList.remove('active');if(dest){const b=board.getBoundingClientRect();wireDrag.points.push(center(dest));links.push({a:from.dataset.id,b:dest.dataset.id,type:wireDrag.type,points:wireDrag.points.map(p=>({x:p.x/b.width,y:p.y/b.height}))});play('connect')}else if(from.classList.contains('rail-tap')&&!links.some(l=>l.a===from.dataset.id||l.b===from.dataset.id))from.remove();wireDrag=null;const s=solve();if(s.short||s.neutralEarth)play('fault');update()}if(motorDrag&&motorDrag.id===e.pointerId){let a=plug.getBoundingClientRect(),b=socket.getBoundingClientRect(),d=Math.hypot(a.left+a.width/2-(b.left+b.width/2),a.top+a.height/2-(b.top+b.height/2));plugged=d<105;if(plugged){plugOffset.x+=b.left+b.width/2-(a.left+a.width/2);plugOffset.y+=b.top+b.height/2-(a.top+a.height/2);plug.style.transform=`translate(${plugOffset.x}px,${plugOffset.y}px)`;play('plug')}motorDrag=null;update();if(diagnose().cls==='hint ok')play('success')}}
function railStart(e){e.preventDefault();audio();const bus=e.currentTarget;bus.setPointerCapture?.(e.pointerId);const r=bus.getBoundingClientRect(),tap=document.createElement('button'),kind=bus.dataset.bus,type=kind==='L'?'brown':kind==='N'?'blue':'earth';tap.className='terminal rail-tap';tap.dataset.id='tap'+kind+(++tapSeq);tap.dataset.bus=kind;tap.setAttribute('aria-label','Derivación '+kind);tap.style.left=Math.max(22,Math.min(r.width-22,e.clientX-r.left))+'px';bus.append(tap);tap.addEventListener('pointerdown',wireStart);wireDrag={start:tap,type,id:e.pointerId,points:[center(tap)]};tap.classList.add('active');draw()}
plug.addEventListener('pointerdown',e=>{e.preventDefault();audio();plug.setPointerCapture?.(e.pointerId);motorDrag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:plugOffset.x,oy:plugOffset.y}});fixedTerms.forEach(t=>t.addEventListener('pointerdown',wireStart));buses.forEach(b=>b.addEventListener('pointerdown',railStart));board.addEventListener('pointerdown',nearestWireStart,true);board.addEventListener('pointermove',pointerMove);board.addEventListener('pointerup',pointerEnd);board.addEventListener('pointercancel',pointerEnd);
keys.forEach((key,i)=>key.onclick=()=>{closed[i]=!closed[i];play('switch');update();if(solve().short)play('fault')});undo.onclick=()=>{if(links.length){links.pop();play('remove');update()}};sound.onclick=()=>{audioEnabled=!audioEnabled;sound.setAttribute('aria-pressed',String(audioEnabled));sound.textContent=audioEnabled?'🔊 Sonidos':'🔇 Silenciado'};
function place(el,x,y,r=0){el.style.left=x+'%';el.style.top=y+'%';el.style.right='auto';el.style.bottom='auto';el.style.transform='translate(-50%,-50%) rotate('+r+'deg)'}function reset(){links=[];wireDrag=null;motorDrag=null;closed=[false,false];plugged=false;selected='brown';document.querySelectorAll('.rail-tap').forEach(t=>t.remove());tapSeq=0;plugOffset={x:0,y:0};plug.style.transform='translate(0,0)';choices.forEach(c=>c.setAttribute('aria-pressed',String(c.dataset.type==='brown')));const compact=matchMedia('(max-width:950px) and (orientation:landscape)').matches;place(unit,50,compact?58:57,0);place(rod,compact?9:11,compact?72:78,0);place(motor,compact?84:84,compact?82:79,0);const slots=(compact?[[25,56],[65,56]]:[[17,36],[83,36]]).sort(()=>Math.random()-.5),spread=compact?2:4;lamps.forEach((lamp,i)=>place(lamp,slots[i][0]+Math.random()*spread-spread/2,slots[i][1]+Math.random()*spread-spread/2,Math.round(Math.random()*20-10)));update()}document.querySelector('#reset').onclick=()=>{play('remove');reset()};new ResizeObserver(draw).observe(board);reset();
})();
